<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="QT-INHD-LT0694" failures="0" tests="2" name="com.PTMWeb.testcases.TC_03_User_downloads_the_Liabilities_issues_Report_by_searching_with_Reason" time="53.097" errors="1" timestamp="2022-08-22T11:41:36 IST" skipped="0">
  <testcase classname="com.PTMWeb.testcases.TC_03_User_downloads_the_Liabilities_issues_Report_by_searching_with_Reason" name="TC_03_User_downloads_the_Liabilities_issues_Report_by_searching_with_Reason" time="50.788"/>
  <system-out/>
  <testcase classname="com.PTMWeb.testcases.TC_03_User_downloads_the_Liabilities_issues_Report_by_searching_with_Reason" name="quitbrowser" time="2.309">
    <error message="Cannot invoke &quot;atu.testrecorder.media.MovieWriter.close()&quot; because &quot;this.w&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "atu.testrecorder.media.MovieWriter.close()" because "this.w" is null
at atu.testrecorder.ATUTestRecorder.stop(ATUTestRecorder.java:462)
at com.PTMWeb.utilities.Baseclass.quitbrowser(Baseclass.java:117)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:222)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:131)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- quitbrowser -->
  <system-out/>
</testsuite> <!-- com.PTMWeb.testcases.TC_03_User_downloads_the_Liabilities_issues_Report_by_searching_with_Reason -->
